// src/TokenType.java

public enum TokenType {
    KEYWORD, IDENTIFIER, INTEGER_LITERAL, FLOAT_LITERAL, STRING_LITERAL,
    CHAR_LITERAL, BOOLEAN_LITERAL, OPERATOR, PUNCTUATOR, COMMENT,
    WHITESPACE, EOF, ERROR
}
